### ISSUE TITLE
Support this board in ICEStudio

### ISSUE THREAD

**Issue by benitoss** [tinyvision-ai-inc/pico-ice#28]
I would like to contribute to this proyect giving support to this board in ICEStudio.
I have already experience because I added the ColorBoard FPGAs (ECP) in IceStudio and Appio
Please contact with me for more details 

Fernando Mosquera (benitoss@gmail.com)

**Comment by josuah** [comment]
Apologies for the long delay! I only noticed this now. Will come back to you shortly, if the proposition still holds of course...
Note, I am not the project main author, but do a lot of house cleaning.

**Comment by vr2045** [comment]
Sure, that would be great! I'll email you...

**Comment by benitoss** [comment]
The board is already supported by IceStudio/Apio
