### ISSUE TITLE
PMOD numbering mismatch in pinout diagram

### ISSUE THREAD

**Issue by gumpu** [tinyvision-ai-inc/pico-ice#37]
In the legenda of the  pinout diagram   https://github.com/tinyvision-ai-inc/pico-ice/blob/main/Docs/pinout/pinout.svg
it says that:  PMOD 3 is a "RP PMOD" and PMOD 4 is a "RP-ICE PMOD".

However the diagram itself seems to indicate the opposite; The gray box labeled 4 contains only RP labels, while the box labeled 3 contains both RP and ICE labels.

**Comment by josuah** [comment]
Fixed by https://github.com/tinyvision-ai-inc/pico-ice/commit/99993c1379a183c67c775891324ef615c6d16f75

Thank you for reporting!

Thanks to https://pinout.readthedocs.io/en/latest/ for allowing this to be a 2-line patch!
