### ISSUE TITLE
10ms/byte delay when dealing with ACM1

### ISSUE THREAD

**Issue by MrJake222** [tinyvision-ai-inc/pico-ice#42]
**moved from pico-ice-sdk**

Hi,

I'm sending/receiving 2-byte frames to/from iCE40 via `ACM1` virtual serial port. The `serial.read` function always stalls for 20ms. I think it's related to the SDK (not Python or kernel) because `ACM0` doesn't have this delay.

![image](https://github.com/tinyvision-ai-inc/pico-ice-sdk/assets/7581790/e536c200-b211-4d56-9fb4-041af2f1e301)

# Resolution
Turns out waiting for user input in main loop is not the best strategy.
https://github.com/tinyvision-ai-inc/pico-ice/blob/f9bd6e648ee60ef808dcea329a99da570e69a52e/Firmware/pico-ice-default/main.c#L58-L62
 That's not how this works. ```getchar_timeout_us``` calls ```stdio_get_until``` which [waits internally](https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2_common/pico_stdio/stdio.c#L117-L137)!

**Comment by josuah** [comment]
Thank you, great insight about `stdio_get_until` busy looping in the "driver"/"hal"/"sdk" code!
